# Generated by Django 3.2.8 on 2022-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20220228_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('AV', 'Approved'), ('PD', 'Pending'), ('RJ', 'Rejected')], default='PD', max_length=2),
        ),
    ]
